name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # step for tags (v*)
      - name: Extract version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Fetch and rebuild builder
        run: |
          docker pull ghcr.io/buckaroobanzay/minetest-wasm:builder || true
          docker build . --target builder -t ghcr.io/buckaroobanzay/minetest-wasm:builder
          docker push ghcr.io/buckaroobanzay/minetest-wasm:builder

      - name: Build and push tag
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          docker build . -t ghcr.io/buckaroobanzay/minetest-wasm:${RELEASE_VERSION}
          docker push ghcr.io/buckaroobanzay/minetest-wasm:${RELEASE_VERSION}

      # step for main/latest (docker only)
      - name: Build and push latest docker image
        if: success() && github.ref == 'refs/heads/main'
        run: |
          docker build . -t ghcr.io/buckaroobanzay/minetest-wasm:latest
          docker push ghcr.io/buckaroobanzay/minetest-wasm:latest
